name: deploy-container

on:
    push:
        branches:
            - master
        paths:
            - "packages/container/**"
    workflow_dispatch: # Add this section for manual triggering

defaults:
    run:
        working-directory: packages/container

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: Set up Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: "15.14.0"

            - run: npm install
            - run: npm run build

            - uses: shinyinc/action-aws-cli@v1.2
              env:
                  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  AWS_DEFAULT_REGION: ""
